name: streamlit
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit
      - pandas
      - matplotlib
      - wordcloud
      - spacy==3.8.2
      - nltk
      - transformers==4.37.2
